global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flask_app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["flask_app:5000"]

  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
